# ==============================================================
# vLLM Configuration file:
# https://docs.vllm.ai/en/stable/configuration/serve_args/#configuration-file
# vLLM CLI args:
# https://docs.vllm.ai/en/stable/cli/serve/
# ==============================================================

# model: Qwen/Qwen3.5-0.8B
# model: facebook/opt-125m
model: Qwen/Qwen3-0.6B
dtype: auto
max_model_len: 1024
max_num_batched_tokens: 256
gpu_memory_utilization: 0.7
enable_prefix_caching: false
trust_remote_code: true

enforce_eager: true
# language_model_only: true
# kv_cache_memory_bytes: 2G
# kv_cache_dtype: bfloat16


# ==============================================================
# vLLM Reasoning Outputs:
# https://docs.vllm.ai/en/stable/features/reasoning_outputs/
# reasoning_parser: qwen3
# ==============================================================

# hf_token: ""
# host: 0.0.0.0
# port: 8000
