# ==============================================================
# vLLM Configuration file:
# https://docs.vllm.ai/en/stable/configuration/serve_args/#configuration-file
# vLLM CLI args:
# https://docs.vllm.ai/en/stable/cli/serve/
# ==============================================================

# model: Qwen/Qwen3.5-2B
model: Qwen/Qwen3.5-0.8B
dtype: auto
max_model_len: auto
max_num_batched_tokens: 1024
gpu_memory_utilization: 0.7
tensor_parallel_size: 1
trust_remote_code: true

# ==============================================================
# vLLM Tool Calling docs:
# https://docs.vllm.ai/en/stable/features/tool_calling/?h=tool#automatic-function-calling
# ==============================================================
enable_auto_tool_choice: true
tool_call_parser: hermes
# tool_call_parser: qwen3_coder
# tool_call_parser: openai


# ==============================================================
# vLLM Reasoning Outputs:
# https://docs.vllm.ai/en/stable/features/reasoning_outputs/
# reasoning_parser: qwen3
# ==============================================================

# hf_token: ""
# host: 0.0.0.0
# port: 8000
