services:
  ollama:
    extends:
      file: compose.yml
      service: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]