# https://docs.vllm.ai/en/latest/getting_started/installation/gpu/#set-up-using-docker
# https://docs.vllm.ai/en/latest/deployment/docker/

services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm
    restart: unless-stopped
    ports:
      - ${VLLM_PORT:-8000}:8000
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-../data}/huggingface:/root/.cache/huggingface
      - ${CONFIG_DIR:-../configs}/vllm:/workspace/configs
    ipc: host
    gpus: all
    command:
      - --config
      - /workspace/configs/cuda.yml
    env_file:
      - path: ../.env
        required: false
