# https://docs.sglang.io/docs/hardware-platforms/cpu_server

services:
  sglang:
    extends:
      file: ../llm/compose.sglang.yml
      service: sglang
    image: ghcr.io/sergey21000/sglang-cpu:latest
    gpus: !reset null
    command:
      - --host
      - 0.0.0.0
      - --port
      - ${SGLANG_PORT:-30000}
      - --config
      - /sgl-workspace/configs/cpu.yml
