services:
  # https://prometheus.io/docs/prometheus/latest/installation/#using-docker
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - ${PROMETHEUS_PORT:-9090}:9090
    volumes:
      - ${CONFIG_DIR:-../configs}/prometheus:/etc/prometheus
      - ${CONFIG_DIR:-../configs}/alertmanager:/etc/alertmanager
      - prometheus-storage:/prometheus
    command:
      - '--storage.tsdb.path=/prometheus'
      - '--config.file=/etc/prometheus/prometheus.${LLM_SERVICE:-base}.yml'
      - '--storage.tsdb.retention.time=${PROMETHEUS_RETENTION:-200h}'
      - '--web.enable-lifecycle'
    depends_on:
      - node-exporter
      - alertmanager
    restart: unless-stopped
  
  # https://grafana.com/docs/grafana/latest/setup-grafana/installation/docker/#run-grafana-via-docker-compose
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - ${GRAFANA_PORT:-3000}:3000
    volumes:
      - ${CONFIG_DIR:-../configs}/grafana/datasources:/etc/grafana/provisioning/datasources
      - ${CONFIG_DIR:-../configs}/grafana/dashboards/config:/etc/grafana/provisioning/dashboards
      - ${CONFIG_DIR:-../configs}/grafana/dashboards/json:/var/lib/grafana/dashboards
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/system.json
      - GF_USERS_ALLOW_SIGN_UP=false
      # - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/${LLM_SERVICE:-base}.json
    depends_on:
      - prometheus
    env_file:
      - path: ../.env
        required: false
    restart: unless-stopped
  
  # https://prometheus.io/docs/guides/node-exporter/
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - ${NODE_EXPORTER_PORT:-9100}:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    restart: unless-stopped
  
  # https://prometheus.io/docs/alerting/latest/overview/
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - ${ALERTMANAGER_PORT:-9093}:9093
    volumes:
      - ${CONFIG_DIR:-../configs}/alertmanager:/etc/alertmanager
      - alertmanager-storage:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://localhost:${ALERTMANAGER_PORT:-9093}'
    restart: unless-stopped

  # https://github.com/grafana/loki/tree/main/examples/getting-started
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - ${LOKI_PORT:-3100}:3100
    volumes:
      - ${CONFIG_DIR:-../configs}/loki:/etc/loki
      - loki-storage:/loki
    command:
      - '-config.file=/etc/loki/config.yml'
    restart: unless-stopped

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - ${ALLOY_UI_PORT:-12345}:12345
    volumes:
      - ${CONFIG_DIR:-../configs}/alloy:/etc/alloy
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.yml
    depends_on:
      - loki
    restart: unless-stopped

volumes:
  prometheus-storage:
  grafana-storage:
  alertmanager-storage:
  loki-storage: