services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - ${PROMETHEUS_PORT:-9090}:9090
    volumes:
      - ${CONFIG_DIR:-../configs}/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - ${GRAFANA_PORT:-3000}:3000
    volumes:
      - ${CONFIG_DIR:-../configs}/grafana/datasources:/etc/grafana/provisioning/datasources
      - ${CONFIG_DIR:-../configs}/grafana/dashboards/config:/etc/grafana/provisioning/dashboards
      - ${CONFIG_DIR:-../configs}/grafana/dashboards/json:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_AUTH_BASIC_ENABLED=false
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/sglang-dashboard.json
      
      # - GF_SECURITY_ADMIN_USER=admin
      # - GF_SECURITY_ADMIN_PASSWORD=admin
      # - GF_INSTALL_PLUGINS=grafana-piechart-panel
    depends_on:
      - prometheus