services:
  infinity:
    extends:
      file: ../services/compose.infinity.yml
      service: infinity
    build:
      args:
        BASE_IMAGE: michaelf34/infinity:latest-cpu
    image: local/infinity-updated:latest-cpu
    gpus: !reset null
