services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: host
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-../data}/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    network_mode: host
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-../data}/grafana/datasources:/etc/grafana/provisioning/datasources
      - ${DOCKER_VOLUME_STORAGE:-../data}/grafana/dashboards/config:/etc/grafana/provisioning/dashboards
      - ${DOCKER_VOLUME_STORAGE:-../data}/grafana/dashboards/json:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_AUTH_BASIC_ENABLED=false
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/sglang-dashboard.json
    depends_on:
      - prometheus