services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: unless-stopped
    ports:
      - ${QDRANT_PORT:-6333}:6333
    volumes:
      - qdrant:/qdrant/storage

volumes:
  qdrant: