services:
  prometheus:
    extends:
      file: ../services/compose.monitoring.yml
      service: prometheus
    command:
      - '--storage.tsdb.path=/prometheus'
      - '--config.file=/etc/prometheus/prometheus.llamacpp.yml'
  
  grafana:
    extends:
      file: ../services/compose.monitoring.yml
      service: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_AUTH_BASIC_ENABLED=false
      - GF_USERS_ALLOW_SIGN_UP=false
    # depends_on:
      # - prometheus