services:
  openwebui:
    extends:
      file: compose.yml
      service: openwebui
      
  ollama:
    extends:
      file: compose.yml
      service: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  open-webui:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLUME_STORAGE:-../data}/openwebui