# ==============================================================
# SGLang server arguments:
# https://docs.sglang.io/advanced_features/server_arguments.html
# ==============================================================

model-path: Qwen/Qwen3.5-0.8B
enable-metrics: true
log-requests: true
trust-remote-code: true
dtype: auto
device: cpu
context-length: 4096

# tensor-parallel-size: 1
# mem-fraction-static: 0.7
# max-total-tokens: none
# chunked-prefill-size: -1
# kv-cache-dtype: auto
# quantization: none
# cpu-offload-gb: 0

# enable-metrics: true
# log-requests: true
