# ==============================================================
# SGLang server arguments:
# https://docs.sglang.io/advanced_features/server_arguments.html
# ==============================================================

# model-path: Qwen/Qwen3.5-2B
model-path: Qwen/Qwen3.5-0.8B
tensor-parallel-size: 1
enable-metrics: true
log-requests: true
trust-remote-code: true
dtype: auto
device: cuda

# tensor-parallel-size: 1
# mem-fraction-static: 0.7
# context-length: 4096
# max-total-tokens: none
# chunked-prefill-size: -1
# kv-cache-dtype: auto
# quantization: none
# cpu-offload-gb: 0

# enable-metrics: true
# log-requests: true

# для видеокарт Blackwell на момент тестирования поддерживаются только бэкенды "triton" или "trtllm_mha"
# https://docs.sglang.io/advanced_features/server_arguments.html#kernel-backends-attention-sampling-grammar-gemm
# https://docs.sglang.io/advanced_features/attention_backend.html
attention-backend: triton
