model-path: Qwen/Qwen3.5-0.8B
tensor-parallel-size: 1
enable-metrics: true
log-requests: true
trust-remote-code: true
dtype: auto
device: cuda

# для видеокарт Blackwell на момент тестирования поддерживаются только бэкенды triton or trtllm_mha
# https://docs.sglang.io/advanced_features/server_arguments.html#kernel-backends-attention-sampling-grammar-gemm
# https://docs.sglang.io/advanced_features/attention_backend.html
attention-backend: triton
