services:
  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm
    restart: unless-stopped
    ports:
      - ${ANYTHINGLLM_PORT:-3001}:3001
    volumes:
      - anythingllm_storage:/app/server/storage
      - ${CONFIG_DIR:-../configs}/anythingllm/.env:/app/server/.env
    environment:
      - STORAGE_DIR=/app/server/storage
      - OLLAMA_BASE_URL=http://ollama:11434
    env_file:
      - path: ../.env
        required: false

volumes:
  anythingllm_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLUME_STORAGE:-../data}/anythingllm_