services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - ${OPENWEBUI_PORT:-3000}:8080
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    env_file:
      - path: ../.env
        required: false

volumes:
  open-webui:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DOCKER_VOLUME_STORAGE:-../data}/openwebui