# https://docs.vllm.ai/en/latest/getting_started/installation/cpu/#set-up-using-docker

name: Build and Push Docker (vLLM CPU)

on: workflow_dispatch

permissions:
  contents: write
  packages: write

jobs:
  docker-cpu:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout vLLM source
        uses: actions/checkout@v7
        with:
          repository: vllm-project/vllm
          ref: main
          path: .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push CPU image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: docker/Dockerfile.cpu
          push: true
          pull: true
          platforms: linux/amd64
          build-args: |
            VLLM_CPU_X86=false
          tags: |
            ghcr.io/${{ github.repository_owner }}/vllm-cpu:latest
